# https://github.com/php-actions/phpstan
name: PHPStan - PHP Static Analysis

on: [pull_request]
# Allow manually triggering the workflow.
#  workflow_dispatch:

jobs:
  phpstan:
    name: "PHP: 7.4 | PHPStan"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PHPSTAN
        uses: php-actions/phpstan@v3
        with:
          path: ./libraries
          level: 7
