# This is a basic workflow to help you get started with Actions

name: Super Linter Slim

# Controls when the workflow will run
on: push
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  super-lintld:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: chckout code
      uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
    - name: Super-Linter
      uses: github/super-linter/slim@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        
      

    
